const DATE_FULL_FORMAT = 'dd-MM-yyyy';
const DATE_FULL_FORMAT_DATEPICKET = 'DD-MM-YYYY';
const DATE_FULL_YEAR_FORMAT = 'yyyy';

export { DATE_FULL_FORMAT, DATE_FULL_YEAR_FORMAT, DATE_FULL_FORMAT_DATEPICKET }