const TIME_HOURS_MINUTES_FORMAT = 'HH:mm';
const TIME_HOURS_FORMAT = 'HH';
const TIME_MINUTES_FORMAT = 'mm';

const TIME_START_WORK = '09:00';
const TIME_END_WORK = '17:00';

export { TIME_HOURS_MINUTES_FORMAT, TIME_HOURS_FORMAT, TIME_MINUTES_FORMAT, TIME_START_WORK, TIME_END_WORK }